layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

paginate: 9
paginate_path: "/page-:num/"

google_analytics: UA-32191131-9
google_verify: 9lmiazHczMChihSqOIRvBkz8a833OZ8hi1Jhv1YHU3w

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 7
  exclude:
    archived: false
    forks: true
    projects:
      - devexps.github.io

# social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: kthangvd
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: kthangvd
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: kthangvd
  # unsplash: your_username
  # vk: your_username
  website: https://devexps.com
  # youtube: your_username

topics:
  - name: Golang
    web_url: https://golang.org/
    image_url: /assets/topics/golang-logo.svg

  - name: Flutter
    web_url: https://flutter.dev/
    image_url: /assets/topics/flutter-logo.png

  - name: Unity
    web_url: https://unity.com/
    image_url: /assets/topics/unity-logo.png
