layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
      - devexps.github.io

# social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: kthangvd
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: kthangvd
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: kthangvd
  # unsplash: your_username
  # vk: your_username
  website: https://devexps.com
  # youtube: your_username

topics:
  - name: Golang
    web_url: https://golang.org/
    image_url: https://golang.org/lib/godoc/images/go-logo-blue.svg

  - name: Flutter
    web_url: https://flutter.dev/
    image_url: https://juststickers.in/wp-content/uploads/2019/01/flutter.png

  - name: Unity
    web_url: https://unity.com/
    image_url: https://technicalhub.io/images/codeheat3.0-courses/even_session46.png
